import { createContext, useContext, useState, useEffect } from "react";

// ─── Supported languages ───────────────────────────────────────────────────────
export type Lang = "fr" | "ar";

// ─── Zones ────────────────────────────────────────────────────────────────────
export const ZONES = ["Toutes les zones", "UMA SOUKRA", "El Menzah", "La Marsa", "Ariana", "Ennasr"] as const;
export type Zone = typeof ZONES[number];

// ─── Context ──────────────────────────────────────────────────────────────────
interface AppContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  zone: Zone;
  setZone: (z: Zone) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const AppContext = createContext<AppContextValue>({
  lang: "fr",
  setLang: () => {},
  zone: "Toutes les zones",
  setZone: () => {},
  t: (k) => k,
});

// ─── Translations ──────────────────────────────────────────────────────────────
const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.localisation": "Localisation",
    "nav.topology": "Topologie Réseau",
    "nav.alerts": "Alertes",
    "nav.equipements": "Équipements",
    "nav.materials": "Inventaire",
    "nav.users": "Gestion Utilisateurs",
    "nav.logout": "Déconnexion",

    // Layout
    "layout.session": "Session active",
    "layout.all_zones": "Toutes les zones",
    "layout.zone_label": "Zone",
    "layout.theme_dark": "Mode sombre",
    "layout.theme_light": "Mode clair",
    "layout.dark_enabled": "Mode sombre activé !",
    "layout.light_enabled": "Mode clair activé !",
    "layout.disconnected": "Déconnexion réussie.",
    "layout.bell_ok": "Réseau Nominal : Aucune anomalie active sur la plaque {zone}.",
    "layout.bell_alerts": "Supervision : {n} alerte(s) active(s) détectée(s) !",
    "layout.access_denied": "Accès Restreint",
    "layout.access_denied_msg": "Votre profil de {role} ne dispose pas des privilèges nécessaires pour accéder au module \"{module}\".",
    "layout.allowed_roles": "Rôles autorisés pour ce module :",
    "layout.switch_account": "Changer de compte / Tester un autre rôle",
    "layout.go_home": "Retour à l'accueil",
    "layout.loading": "Chargement de l'espace de travail…",

    // Dashboard
    "dash.title": "Tableau de Bord",
    "dash.subtitle": "FiberTrack IQ · Supervision réseau FTTH",
    "dash.kpi.connections": "Raccordements Actifs",
    "dash.kpi.connections_desc": "Lignes abonnés connectées",
    "dash.kpi.fdt": "Boîtiers FDT / BPI",
    "dash.kpi.fdt_desc": "Hubs optiques déployés",
    "dash.kpi.incidents": "Supervision Incidents",
    "dash.kpi.incidents_desc": "Alertes actives non résolues",
    "dash.kpi.stock": "Matériels Faibles",
    "dash.kpi.stock_desc": "Articles en rupture de stock",
    "dash.chart.olt_title": "Utilisation Capacités OLT",
    "dash.chart.olt_desc": "Ratio de partage actif par port de carte OLT (max 64)",
    "dash.chart.olt_subscribers": "Abonnés Actifs",
    "dash.chart.olt_capacity": "Capacité Max",
    "dash.chart.inventory_title": "Répartition Inventaire",
    "dash.chart.inventory_desc": "Proportions des stocks disponibles par matériel",
    "dash.live_title": "Supervision en direct",
    "dash.live_link": "Voir toutes les alertes →",
    "dash.no_alerts": "Aucune alerte en cours. Le réseau est sain.",
    "dash.actions_title": "Actions opérationnelles",
    "dash.action_map": "Visualiser la carte",
    "dash.action_map_desc": "Géolocalisation des boîtes et routes",
    "dash.action_inventory": "Inventaire matériel",
    "dash.action_inventory_desc": "Journaliser entrées/sorties & scanner QR",
    "dash.footer": "SOTETEL FTTH Digitalization v2.0.0 · Session SQLite locale sécurisée.",
    "dash.loading": "Chargement des métriques…",

    // Alerts
    "alerts.title": "Alertes Réseau",
    "alerts.search_ph": "Rechercher des alertes…",
    "alerts.export": "📥 Exporter",
    "alerts.declare": "+ Déclarer anomalie",
    "alerts.tab_all": "Toutes les alertes",
    "alerts.tab_open": "Nouvelles",
    "alerts.tab_inprog": "Acquittées",
    "alerts.tab_resolved": "Résolues",
    "alerts.filter_severity": "Filtrer par gravité :",
    "alerts.filter_all": "Toutes les gravités",
    "alerts.filter_critical": "Critique",
    "alerts.filter_warning": "Avertissement",
    "alerts.filter_info": "Information",
    "alerts.found": "{n} alertes trouvées",
    "alerts.col_id": "ID",
    "alerts.col_severity": "Sévérité",
    "alerts.col_message": "Message",
    "alerts.col_equipment": "Équipement",
    "alerts.col_status": "Statut",
    "alerts.col_created": "Créé le",
    "alerts.col_actions": "Actions",
    "alerts.status_open": "Nouvelle",
    "alerts.status_inprog": "Acquittée",
    "alerts.status_resolved": "Résolue",
    "alerts.assign": "Assigner",
    "alerts.reassign": "Réassigner",
    "alerts.resolve": "Résoudre",
    "alerts.signal_ok": "Signal Rétabli",
    "alerts.none": "Aucune alerte disponible.",
    "alerts.loading": "Supervision des signaux optiques…",
    "alerts.per_page": "Éléments par page:",
    "alerts.assign_title": "Assigner un technicien",
    "alerts.tech_available": "Techniciens Disponibles",
    "alerts.declare_title": "Déclarer un Incident",
    "alerts.field_message": "Message d'anomalie",
    "alerts.field_message_ph": "ex. Signal optique interrompu…",
    "alerts.field_severity": "Niveau de gravité",
    "alerts.field_bpi": "Code PBO / BPI (Optionnel)",
    "alerts.field_zone": "Zone",
    "alerts.submit": "Enregistrer l'incident",
    "alerts.otdr_title": "Réflectométrie Optique OTDR (Diagnostic)",
    "alerts.otdr_dist": "Distance Incident",
    "alerts.otdr_atten": "Affaiblissement Total",
    "alerts.otdr_wavelength": "Longueur d'onde",
    "alerts.otdr_nominal": "Nominal",
    "alerts.export_success": "Données d'alertes exportées au format CSV !",
    "alerts.assign_success": "Incident assigné à {tech}",
    "alerts.resolve_success": "Incident résolu avec succès !",
    "alerts.create_success": "Nouvelle alerte déclarée et enregistrée !",

    // Topology
    "topo.title": "Topologie Réseau & Analyse d'Impact",
    "topo.subtitle": "Visualisation hiérarchique GPON (OLT ➔ FDT ➔ PBO/BPI ➔ ONT)",
    "topo.new_path": "Nouveau Chemin",
    "topo.fault_on": "Analyseur Panne",
    "topo.fault_off": "Désactiver Analyseur",
    "topo.view_tree": "Vue Hiérarchique GPON",
    "topo.view_heatmap": "⚡ Analyseur Signal & Atténuation",
    "topo.node_title": "Détails du Nœud Sélectionné",
    "topo.click_hint": "Cliquez sur un nœud pour voir ses statistiques GPON.",
    "topo.subscribers": "Abonnés",
    "topo.pbo_boxes": "Boîtes PBO",
    "topo.lines": "Lignes",
    "topo.loading": "Chargement de la topologie réseau…",
    "topo.impact": "Impact Analyseur",
    "topo.impact_clients": "Impact : {n} Clients",
    "topo.modal_title": "Nouveau Chemin Optique",
    "topo.modal_subtitle": "Définir un nouveau chemin de liaison GPON",
    "topo.field_name": "Nom du chemin",
    "topo.field_name_ph": "Ex: Chemin-OLT-FDT-BPI-42",
    "topo.field_olt": "Port OLT",
    "topo.field_olt_ph": "Ex: 3",
    "topo.field_fdt": "FDT (Cabinet)",
    "topo.field_fdt_ph": "Sélectionner un FDT…",
    "topo.field_bpi": "BPI de destination",
    "topo.field_bpi_ph": "Ex: 42",
    "topo.field_length": "Longueur estimée (km)",
    "topo.field_length_ph": "Ex: 1.8",
    "topo.field_notes": "Notes",
    "topo.field_notes_ph": "Notes techniques optionnelles…",
    "topo.btn_cancel": "Annuler",
    "topo.btn_save": "Créer le chemin",
    "topo.success": "Chemin optique créé avec succès !",
    "topo.err_required": "Veuillez remplir tous les champs requis.",
    "topo.detail_olt": "Port OLT Central",
    "topo.detail_capacity": "Capacité totale",
    "topo.detail_sectors": "Secteurs d'activité",
    "topo.detail_type": "Type de matériel",
    "topo.detail_fdt": "FDT Cabinet",
    "topo.detail_pbo_count": "Nombre de PBO raccordés",
    "topo.detail_parent_fdt": "Parent FDT",
    "topo.detail_subscribers": "Abonnés connectés",
    "topo.alarm_active": "Alarme Active",
    "topo.signal_ok": "Signal Nominal",
    "topo.signal_ok_desc": "Faisceau optique optimal. Aucune anomalie.",
    "topo.heatmap_title": "Heatmap Signaux Transceivers (ONT)",
    "topo.heatmap_desc": "{n} jarretières actives",
    "topo.good": "Excellent",
    "topo.avg": "Moyen",
    "topo.bad": "Hors-Ligne",
    "topo.port_label": "Jarretière #",
    "topo.subscriber": "Abonné",
    "topo.floor": "Étage",
    "topo.bpi_box": "Boîtier BPI",
    "topo.parent_fdt": "FDT Parent",
    "topo.link_budget": "Budget de Liaison",
    "topo.alert_on_bpi": "⚠ Alerte active sur {bpi}. Liaison coupée.",
    "topo.view_calculator": "🧮 Calculateur Budget Optique",
    "topo.calc_title": "Calculateur de Budget & Pertes Optiques",
    "topo.calc_desc": "Simulez l'atténuation totale théorique sur la liaison GPON de bout en bout",
    "topo.calc_tx_power": "Puissance Émetteur OLT (dBm)",
    "topo.calc_wavelength": "Longueur d'onde active",
    "topo.calc_fiber_len": "Distance de fibre (km)",
    "topo.calc_splitter": "Ratio du Splitter Optique",
    "topo.calc_splices": "Nombre de Soudures (Épissures)",
    "topo.calc_connectors": "Nombre de Connecteurs rapides",
    "topo.calc_margin": "Marge de sécurité (dB)",
    "topo.calc_total_loss": "Atténuation Totale estimée",
    "topo.calc_rx_power": "Puissance Reçue à l'ONT (dBm)",
    "topo.calc_status": "État théorique du lien",
    "topo.calc_diagram": "Profil de perte optique",
    "nav.guide": "Guide Utilisateur",
    "guide.title": "Guide Pratique FiberNMS",
    "guide.subtitle": "Habilitations et modes opératoires par Rôle",
    "guide.tab_admin": "Administrateur",
    "guide.tab_operator": "Opérateur TT",
    "guide.tab_manager": "Chef de Projet",
    "guide.tab_tech": "Technicien terrain",
    "guide.admin_desc": "Supervision de la sécurité et intégrité de la plateforme.",
    "guide.operator_desc": "Gestion physique et logistique du réseau.",
    "guide.manager_desc": "Supervision stratégique et ingénierie optique.",
    "guide.tech_desc": "Interventions physiques et diagnostic direct sur site.",

    // Equipment
    "equip.title": "Gestion des Équipements",
    "equip.loading": "Chargement des équipements…",
    "equip.search_ph": "Rechercher par Numéro de Série, QR, ou Nom",
    "equip.add": "+ Ajouter Équipement",
    "equip.scan_title": "Scan Rapide",
    "equip.scan_desc": "Scanner le code QR pour identifier",
    "equip.filter_type": "Filtrer par type :",
    "equip.filter_all": "Tous",
    "equip.col_serial": "Numéro de Série",
    "equip.col_name": "Nom",
    "equip.col_type": "Type",
    "equip.col_manufacturer": "Fabricant",
    "equip.col_zone": "Zone",
    "equip.col_status": "Statut",
    "equip.col_actions": "Actions",
    "equip.status_active": "Actif",
    "equip.status_fault": "Anomalie",
    "equip.no_equip": "Aucun équipement disponible dans cette catégorie.",
    "equip.modal_detail_title": "Fiche Technique Matériel",
    "equip.tab_specs": "Fiche Technique",
    "equip.tab_splice": "🛠️ Cassette de Soudure",
    "equip.detail_name": "Nom d'équipement",
    "equip.detail_type": "Type",
    "equip.detail_parent": "Raccordement parent",
    "equip.detail_gps": "Position GPS",
    "equip.detail_subscribers": "Capacité / Raccordements actifs",
    "equip.detail_subscribers_count": "{n} abonnés",
    "equip.modal_add_title": "Enregistrer un Équipement",
    "equip.field_type": "Type matériel",
    "equip.field_name": "Nom / Code unique",
    "equip.field_gps": "Coordonnées GPS (Latitude, Longitude)",
    "equip.field_parent_olt": "Carte GPON d'affectation",
    "equip.field_parent_fdt": "Résidence de rattachement",
    "equip.field_parent_bpi": "FDT parent de rattachement",
    "equip.btn_submit": "Enregistrer l'équipement",
    "equip.scanner_title": "Scanner Code QR Équipement",
    "equip.scanner_placeholder": "Recherche de flux vidéo… Caméra locale prête en arrière-plan.",
    "equip.scanner_sim": "Simulateur de Scan (BDD)",
    "equip.scanner_manual": "Ou saisir manuellement (Nom ou SN)",
    "equip.scanner_btn": "Valider",
    "equip.splice_desc": "Sélectionnez une fibre d'entrée (Feeder) et une fibre de sortie (Drop abonnés) pour souder la liaison optique.",
    "equip.splice_feeder": "Entrée (Feeder)",
    "equip.splice_drop": "Sortie (Drop abonnés)",
    "equip.splice_free": "Libre",
    "equip.splice_tube": "Tube {n} ({color})",
    "equip.splice_ok": "OK",

    // Materials
    "mat.title": "Gestion de l'Inventaire",
    "mat.loading": "Chargement de l'inventaire…",
    "mat.kpi_stock": "Articles en stock",
    "mat.btn_replenish": "Demander Réapprovisionnement",
    "mat.kpi_pending": "Mouvements en attente",
    "mat.btn_approve_all": "Tout approuver",
    "mat.kpi_low_stock": "Alertes Stock Bas",
    "mat.btn_show_low": "Voir les articles",
    "mat.btn_show_all": "Tout afficher",
    "mat.tab_history": "Historique des mouvements",
    "mat.tab_catalog": "Catalogue des articles",
    "mat.history_title": "Historique des mouvements de stock",
    "mat.history_filter": "Filtrer l'historique…",
    "mat.history_status_all": "Tous",
    "mat.history_status_pending": "En attente",
    "mat.history_status_approved": "Approuvés",
    "mat.col_date": "Date",
    "mat.col_item": "Article",
    "mat.col_type": "Type",
    "mat.col_qty": "Quantité",
    "mat.col_to": "De/Vers",
    "mat.col_user": "Utilisateur",
    "mat.col_actions": "Actions",
    "mat.status_pending": "Sortie (En attente)",
    "mat.status_approved": "Sortie",
    "mat.local": "Local",
    "mat.no_movements": "Aucun mouvement de stock trouvé.",
    "mat.catalog_title": "Catalogue du stock matériel",
    "mat.catalog_count": "{n} articles répertoriés",
    "mat.btn_scan_qr": "Scan Rapide QR",
    "mat.btn_new_item": "Nouvel Article",
    "mat.catalog_search": "Rechercher par code ou nom de matériel…",
    "mat.col_code": "Code",
    "mat.col_name": "Nom de l'article",
    "mat.col_cat": "Catégorie",
    "mat.col_stock": "Quantité Stock",
    "mat.col_alert": "Seuil Alerte",
    "mat.btn_use": "Utiliser",
    "mat.no_articles": "Aucun article correspondant.",
    "mat.scanner_title": "Scanner Code QR Matériel",
    "mat.scanner_sim": "Simulateur de Scan Rapide (BDD)",
    "mat.scanner_manual": "Ou saisir manuellement",
    "mat.use_title": "Enregistrer une Sortie",
    "mat.use_stock_qty": "Quantité en Stock: ",
    "mat.use_field_qty": "Quantité à prélever",
    "mat.use_field_bpi": "PBO / BPI d'affectation (Optionnel)",
    "mat.use_field_note": "Commentaire / Note d'affectation",
    "mat.use_btn_submit": "Créer la demande de prélèvement",
    "mat.add_title": "Nouvel Article de Stock",
    "mat.add_field_code": "Code unique de l'article",
    "mat.add_field_name": "Désignation de l'article",
    "mat.add_field_cat": "Catégorie matériel",
    "mat.add_field_unit": "Unité de mesure",
    "mat.add_field_stock": "Stock initial",
    "mat.add_field_min": "Seuil minimum d'alerte",
    "mat.add_btn_submit": "Créer l'article dans le catalogue",

    // Users
    "users.title": "Console d'administration",
    "users.subtitle": "Centralisation SQLite, synchronisation Excel, logs d'audit.",
    "users.loading": "Chargement des utilisateurs…",
    "users.badge": "Espace Administrateur",
    "users.tab_users": "Gérer les utilisateurs",
    "users.tab_logs": "Consulter les logs d'audit",
    "users.tab_config": "Configurer le système",
    "users.list_title": "Utilisateurs enregistrés en BDD",
    "users.btn_create": "Créer un compte",
    "users.col_user": "Utilisateur",
    "users.col_email": "Adresse Email",
    "users.col_role": "Attribution du Rôle",
    "users.col_status": "Accès Actif",
    "users.col_actions": "Actions",
    "users.status_active": "Actif",
    "users.status_suspended": "Suspendu",
    "users.logs_title": "Logs d'audit et supervision d'activité",
    "users.log_action": "Utilisateur {user} a effectué une action.",
    "users.log_module": "Module : {module}",
    "users.config_title": "Configuration générale de la supervision",
    "users.config_detect": "Détection automatique des anomalies",
    "users.config_detect_desc": "Scanne automatiquement le réseau GPON toutes les 30 secondes pour détecter des ruptures optiques.",
    "users.excel_sync": "Synchronisation Excel (Deux Voies)",
    "users.excel_sync_desc": "Comparez les divergences structurelles entre votre feuille Excel et la base SQLite ftth.db, puis fusionnez les modifications.",
    "users.excel_status": "Pont Actif",
    "users.excel_dropzone_title": "Glisser-déposer le classeur Excel technique",
    "users.excel_dropzone_desc": "Base de données (1).xlsx ou fichier d'ingénierie optique (max 10 Mo)",
    "users.excel_dropzone_btn": "Parcourir les fichiers",
    "users.excel_details_title": "Divergences Détectées (Résolution des conflits)",
    "users.excel_details_count": "3 Conflits",
    "users.excel_col_type": "Type",
    "users.excel_col_element": "Élément / Propriété",
    "users.excel_col_sqlite": "Valeur Actuelle (SQLite)",
    "users.excel_col_excel": "Nouvelle Valeur (Excel)",
    "users.excel_btn_reset": "Réinitialiser",
    "users.excel_progress_syncing": "Initialisation...",
    "users.excel_success_title": "Base de données SQLite synchronisée avec succès !",
    "users.excel_success_desc": "La fusion du classeur a été finalisée. L'abonné Bloc C30 et les coordonnées du PBO BPI-A7 sont maintenant actifs.",
    "users.excel_btn_submit": "Appliquer la fusion et mettre à jour SQLite",
    "users.config_retention": "Rétention des logs système",
    "users.config_retention_days": "{n} jours",
    "users.modal_create_title": "Créer un Compte",
    "users.field_name": "Nom complet",
    "users.field_email": "Adresse Email unique",
    "users.field_role": "Rôle Habilitation",
    "users.field_password": "Mot de passe",
    "users.btn_submit": "Enregistrer l'utilisateur",

    // Map
    "map.title": "Visualisation Géographique du Réseau",
    "map.tab_zones": "Zones",
    "map.tab_clusters": "Clusters",
    "map.tab_cables": "Câbles",
    "map.search_ph": "Rechercher une local...",
    "map.layers_title": "Couches Réseau",
    "map.layer_style": "Style de la Carte",
    "map.style_osm": "Plan de Ville",
    "map.style_satellite": "Vue Satellite",
    "map.infra": "Infrastructures",
    "map.layer_reliable": "Zones Fiables",
    "map.layer_monitor": "Zones Sous Surveilla...",
    "map.layer_lines": "Lignes Optiques",
    "map.layer_points": "Points d'Accès",
    "map.layer_anomalies": "Segments en anomalie",
    "map.stats_title": "Stats Zone Sélectionnée",
    "map.stats_locations": "Nombre de localisations :",
    "map.stats_faults": "Pannes Actives :",
    "map.stats_coverage": "Couverture :",
    "map.no_data": "Aucune localisation disponible.",

    // Roles
    "role.admin": "Administrateur",
    "role.operator": "Opérateur TT",
    "role.project_manager": "Chef de projet",
    "role.technician": "Technicien",

    // Common
    "common.na": "N/A",
    "common.search": "Rechercher…",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.close": "Fermer",
    "common.confirm": "Confirmer",
    "common.loading": "Chargement…",
    "common.empty": "Aucun résultat.",
    "common.lang_toggle": "عربي",
  },

  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.localisation": "التحديد الجغرافي",
    "nav.topology": "طوبولوجيا الشبكة",
    "nav.alerts": "التنبيهات",
    "nav.equipements": "المعدات",
    "nav.materials": "المخزون",
    "nav.users": "إدارة المستخدمين",
    "nav.logout": "تسجيل الخروج",

    // Layout
    "layout.session": "الجلسة النشطة",
    "layout.all_zones": "جميع المناطق",
    "layout.zone_label": "المنطقة",
    "layout.theme_dark": "الوضع الداكن",
    "layout.theme_light": "الوضع الفاتح",
    "layout.dark_enabled": "تم تفعيل الوضع الداكن!",
    "layout.light_enabled": "تم تفعيل الوضع الفاتح!",
    "layout.disconnected": "تم تسجيل الخروج بنجاح.",
    "layout.bell_ok": "الشبكة طبيعية: لا توجد أعطال نشطة في منطقة {zone}.",
    "layout.bell_alerts": "الإشراف: {n} تنبيه(ات) نشطة مكتشفة!",
    "layout.access_denied": "وصول مقيّد",
    "layout.access_denied_msg": "ملفك الشخصي كـ{role} لا يملك الصلاحيات اللازمة للوصول إلى وحدة \"{module}\".",
    "layout.allowed_roles": "الأدوار المسموح لها بهذه الوحدة:",
    "layout.switch_account": "تغيير الحساب / اختبار دور آخر",
    "layout.go_home": "العودة إلى الرئيسية",
    "layout.loading": "جاري تحميل مساحة العمل…",

    // Dashboard
    "dash.title": "لوحة التحكم",
    "dash.subtitle": "FiberTrack IQ · إشراف شبكة الألياف الضوئية",
    "dash.kpi.connections": "الاشتراكات النشطة",
    "dash.kpi.connections_desc": "خطوط المشتركين المتصلة",
    "dash.kpi.fdt": "صناديق FDT / BPI",
    "dash.kpi.fdt_desc": "مراكز التوزيع الضوئية المنشورة",
    "dash.kpi.incidents": "إشراف الحوادث",
    "dash.kpi.incidents_desc": "تنبيهات نشطة غير محلولة",
    "dash.kpi.stock": "مواد ناقصة",
    "dash.kpi.stock_desc": "مواد في حالة نقص بالمخزن",
    "dash.chart.olt_title": "استخدام سعة OLT",
    "dash.chart.olt_desc": "نسبة المشاركة النشطة لكل منفذ بطاقة OLT (الحد الأقصى 64)",
    "dash.chart.olt_subscribers": "المشتركون النشطون",
    "dash.chart.olt_capacity": "السعة القصوى",
    "dash.chart.inventory_title": "توزيع المخزون",
    "dash.chart.inventory_desc": "نسب المخزون المتاح حسب المواد الرئيسية",
    "dash.live_title": "الإشراف المباشر",
    "dash.live_link": "عرض جميع التنبيهات ←",
    "dash.no_alerts": "لا توجد تنبيهات. الشبكة في حالة طبيعية.",
    "dash.actions_title": "الإجراءات التشغيلية",
    "dash.action_map": "عرض الخريطة",
    "dash.action_map_desc": "الموقع الجغرافي للصناديق والمسارات",
    "dash.action_inventory": "مخزون المواد",
    "dash.action_inventory_desc": "تسجيل الدخول/الخروج ومسح QR",
    "dash.footer": "SOTETEL FTTH Digitalization v2.0.0 · جلسة SQLite محلية آمنة.",
    "dash.loading": "جاري تحميل المؤشرات…",

    // Alerts
    "alerts.title": "تنبيهات الشبكة",
    "alerts.search_ph": "البحث في التنبيهات…",
    "alerts.export": "📥 تصدير",
    "alerts.declare": "+ إعلان عن عطل",
    "alerts.tab_all": "جميع التنبيهات",
    "alerts.tab_open": "جديدة",
    "alerts.tab_inprog": "قيد المعالجة",
    "alerts.tab_resolved": "محلولة",
    "alerts.filter_severity": "تصفية حسب الخطورة:",
    "alerts.filter_all": "جميع مستويات الخطورة",
    "alerts.filter_critical": "حرج",
    "alerts.filter_warning": "تحذير",
    "alerts.filter_info": "معلومات",
    "alerts.found": "{n} تنبيه موجود",
    "alerts.col_id": "المعرف",
    "alerts.col_severity": "الخطورة",
    "alerts.col_message": "الرسالة",
    "alerts.col_equipment": "المعدة",
    "alerts.col_status": "الحالة",
    "alerts.col_created": "تاريخ الإنشاء",
    "alerts.col_actions": "الإجراءات",
    "alerts.status_open": "جديدة",
    "alerts.status_inprog": "قيد المعالجة",
    "alerts.status_resolved": "محلولة",
    "alerts.assign": "تعيين",
    "alerts.reassign": "إعادة تعيين",
    "alerts.resolve": "حل",
    "alerts.signal_ok": "الإشارة مستعادة",
    "alerts.none": "لا توجد تنبيهات.",
    "alerts.loading": "جاري إشراف الإشارات الضوئية…",
    "alerts.per_page": "عناصر لكل صفحة:",
    "alerts.assign_title": "تعيين تقني",
    "alerts.tech_available": "التقنيون المتاحون",
    "alerts.declare_title": "إعلان عن حادثة",
    "alerts.field_message": "رسالة العطل",
    "alerts.field_message_ph": "مثال: انقطاع الإشارة الضوئية…",
    "alerts.field_severity": "مستوى الخطورة",
    "alerts.field_bpi": "رمز PBO / BPI (اختياري)",
    "alerts.field_zone": "المنطقة",
    "alerts.submit": "تسجيل الحادثة",
    "alerts.otdr_title": "قياس الانعكاس الضوئي OTDR (التشخيص)",
    "alerts.otdr_dist": "مسافة الحادثة",
    "alerts.otdr_atten": "التخميد الكلي",
    "alerts.otdr_wavelength": "الطول الموجي",
    "alerts.otdr_nominal": "طبيعي",
    "alerts.export_success": "تم تصدير بيانات التنبيهات بتنسيق CSV!",
    "alerts.assign_success": "تم تعيين الحادثة إلى {tech}",
    "alerts.resolve_success": "تم حل الحادثة بنجاح!",
    "alerts.create_success": "تم إعلان وتسجيل التنبيه الجديد!",

    // Topology
    "topo.title": "طوبولوجيا الشبكة وتحليل التأثير",
    "topo.subtitle": "تصور هرمي GPON (OLT ➔ FDT ➔ PBO/BPI ➔ ONT)",
    "topo.new_path": "مسار جديد",
    "topo.fault_on": "محلل الأعطال",
    "topo.fault_off": "إيقاف المحلل",
    "topo.view_tree": "العرض الهرمي GPON",
    "topo.view_heatmap": "⚡ محلل الإشارة والتخميد",
    "topo.node_title": "تفاصيل العقدة المحددة",
    "topo.click_hint": "انقر على عقدة لعرض إحصائياتها.",
    "topo.subscribers": "مشترك",
    "topo.pbo_boxes": "صندوق PBO",
    "topo.lines": "خط",
    "topo.loading": "جاري تحميل طوبولوجيا الشبكة…",
    "topo.impact": "تحليل التأثير",
    "topo.impact_clients": "التأثير: {n} عميل",
    "topo.modal_title": "مسار بصري جديد",
    "topo.modal_subtitle": "تحديد مسار ربط GPON جديد",
    "topo.field_name": "اسم المسار",
    "topo.field_name_ph": "مثال: Chemin-OLT-FDT-BPI-42",
    "topo.field_olt": "منفذ OLT",
    "topo.field_olt_ph": "مثال: 3",
    "topo.field_fdt": "FDT (الخزانة)",
    "topo.field_fdt_ph": "اختر FDT…",
    "topo.field_bpi": "BPI الوجهة",
    "topo.field_bpi_ph": "مثال: 42",
    "topo.field_length": "الطول التقديري (كم)",
    "topo.field_length_ph": "مثال: 1.8",
    "topo.field_notes": "ملاحظات",
    "topo.field_notes_ph": "ملاحظات تقنية اختيارية…",
    "topo.btn_cancel": "إلغاء",
    "topo.btn_save": "إنشاء المسار",
    "topo.success": "تم إنشاء المسار البصري بنجاح!",
    "topo.err_required": "يرجى ملء جميع الحقول المطلوبة.",
    "topo.detail_olt": "منفذ OLT المركزي",
    "topo.detail_capacity": "السعة الإجمالية",
    "topo.detail_sectors": "قطاعات النشاط",
    "topo.detail_type": "نوع المعدات",
    "topo.detail_fdt": "خزانة FDT",
    "topo.detail_pbo_count": "عدد PBO المتصلة",
    "topo.detail_parent_fdt": "FDT الأم",
    "topo.detail_subscribers": "المشتركون المتصلون",
    "topo.alarm_active": "إنذار نشط",
    "topo.signal_ok": "إشارة طبيعية",
    "topo.signal_ok_desc": "الحزمة الضوئية مثالية. لا توجد أي عطلات.",
    "topo.heatmap_title": "خريطة الحرارة للإشارات (ONT)",
    "topo.heatmap_desc": "{n} وصلة نشطة",
    "topo.good": "ممتاز",
    "topo.avg": "متوسط",
    "topo.bad": "غير متصل",
    "topo.port_label": "وصلة #",
    "topo.subscriber": "المشترك",
    "topo.floor": "الطابق",
    "topo.bpi_box": "صندوق BPI",
    "topo.parent_fdt": "FDT الأم",
    "topo.link_budget": "ميزانية الوصلة",
    "topo.alert_on_bpi": "⚠ إنذار نشط على {bpi}. الوصلة مقطوعة.",
    "topo.view_calculator": "🧮 حاسبة الميزانية الضوئية",
    "topo.calc_title": "حاسبة ميزانية وخسائر الإشارة الضوئية",
    "topo.calc_desc": "محاكاة التخميد الكلي النظري للوصلة الضوئية GPON من البداية إلى النهاية",
    "topo.calc_tx_power": "قوة الإرسال لجهاز OLT (dBm)",
    "topo.calc_wavelength": "الطول الموجي النشط",
    "topo.calc_fiber_len": "مسافة الألياف (كم)",
    "topo.calc_splitter": "نسبة تقسيم الموزع الضوئي",
    "topo.calc_splices": "عدد نقاط اللحام (الوحدات)",
    "topo.calc_connectors": "عدد الموصلات السريعة",
    "topo.calc_margin": "هامش الأمان والسلامة (dB)",
    "topo.calc_total_loss": "التخميد الكلي التقديري",
    "topo.calc_rx_power": "القوة المستلمة عند جهاز ONT (dBm)",
    "topo.calc_status": "حالة الوصلة النظرية",
    "topo.calc_diagram": "مخطط تخميد الإشارة الضوئية",
    "nav.guide": "دليل المستخدم",
    "guide.title": "دليل المستخدم العملي لـ FiberNMS",
    "guide.subtitle": "الصلاحيات وإجراءات العمل الميدانية حسب الدور",
    "guide.tab_admin": "مدير النظام",
    "guide.tab_operator": "مشغل TT",
    "guide.tab_manager": "مدير المشروع",
    "guide.tab_tech": "تقني الميدان",
    "guide.admin_desc": "الإشراف على الأمن والسلامة وسلامة المنصة بالكامل.",
    "guide.operator_desc": "الإدارة المادية واللوجستية للشبكة والمخازن.",
    "guide.manager_desc": "الإشراف الاستراتيجي وتخطيط الألياف والهندسة الضوئية.",
    "guide.tech_desc": "التدخل الميداني المادي والتشخيص الفوري للأعطال في الموقع.",

    // Equipment
    "equip.title": "إدارة المعدات",
    "equip.loading": "جاري تحميل المعدات…",
    "equip.search_ph": "البحث بالرقم التسلسلي، QR، أو الاسم",
    "equip.add": "+ إضافة معدة",
    "equip.scan_title": "المسح السريع",
    "equip.scan_desc": "امسح رمز QR للتعرف على المعدة",
    "equip.filter_type": "تصفية حسب النوع:",
    "equip.filter_all": "الكل",
    "equip.col_serial": "الرقم التسلسلي",
    "equip.col_name": "الاسم",
    "equip.col_type": "النوع",
    "equip.col_manufacturer": "المصنع",
    "equip.col_zone": "المنطقة",
    "equip.col_status": "الحالة",
    "equip.col_actions": "الإجراءات",
    "equip.status_active": "نشط",
    "equip.status_fault": "عطل",
    "equip.no_equip": "لا توجد معدات متوفرة في هذه الفئة.",
    "equip.modal_detail_title": "البطاقة الفنية للمعدات",
    "equip.tab_specs": "البطاقة الفنية",
    "equip.tab_splice": "🛠️ علبة اللحام",
    "equip.detail_name": "اسم المعدة",
    "equip.detail_type": "النوع",
    "equip.detail_parent": "الربط الأب",
    "equip.detail_gps": "موقع GPS",
    "equip.detail_subscribers": "السعة / التوصيلات النشطة",
    "equip.detail_subscribers_count": "{n} مشتركين",
    "equip.modal_add_title": "تسجيل معدة جديدة",
    "equip.field_type": "نوع المعدات",
    "equip.field_name": "الاسم / الرمز الفريد",
    "equip.field_gps": "إحداثيات GPS (خط العرض، خط الطول)",
    "equip.field_parent_olt": "بطاقة GPON المخصصة",
    "equip.field_parent_fdt": "الإقامة المرتبطة",
    "equip.field_parent_bpi": "FDT الأب المرتبط",
    "equip.btn_submit": "تسجيل المعدة",
    "equip.scanner_title": "مسح رمز QR للمعدة",
    "equip.scanner_placeholder": "البحث عن بث الفيديو... الكاميرا المحلية جاهزة في الخلفية.",
    "equip.scanner_sim": "محاكي المسح (قاعدة البيانات)",
    "equip.scanner_manual": "أو الإدخال يدويًا (الاسم أو الرقم التسلسلي)",
    "equip.scanner_btn": "تأكيد",
    "equip.splice_desc": "اختر ليفة إدخال (Feeder) وليفة إخراج (Drop) للحام الوصلة الضوئية.",
    "equip.splice_feeder": "الإدخال (Feeder)",
    "equip.splice_drop": "الإخراج (Drop abonnés)",
    "equip.splice_free": "حرة",
    "equip.splice_tube": "أنبوب {n} ({color})",
    "equip.splice_ok": "تم",

    // Materials
    "mat.title": "إدارة المخزون",
    "mat.loading": "جاري تحميل المخزون…",
    "mat.kpi_stock": "المواد في المخزن",
    "mat.btn_replenish": "طلب إعادة التموين",
    "mat.kpi_pending": "الحركات المعلقة",
    "mat.btn_approve_all": "الموافقة على الكل",
    "mat.kpi_low_stock": "تنبيهات انخفاض المخزون",
    "mat.btn_show_low": "عرض المواد",
    "mat.btn_show_all": "عرض الكل",
    "mat.tab_history": "سجل الحركات",
    "mat.tab_catalog": "كتالوج المواد",
    "mat.history_title": "سجل حركات المخزون",
    "mat.history_filter": "تصفية السجل…",
    "mat.history_status_all": "الكل",
    "mat.history_status_pending": "قيد الانتظار",
    "mat.history_status_approved": "مقبول",
    "mat.col_date": "التاريخ",
    "mat.col_item": "المادة",
    "mat.col_type": "النوع",
    "mat.col_qty": "الكمية",
    "mat.col_to": "من/إلى",
    "mat.col_user": "المستخدم",
    "mat.col_actions": "الإجراءات",
    "mat.status_pending": "إخراج (قيد الانتظار)",
    "mat.status_approved": "إخراج",
    "mat.local": "مستودع",
    "mat.no_movements": "لم يتم العثور على أي حركة مخزون.",
    "mat.catalog_title": "كتالوج مخزون المواد",
    "mat.catalog_count": "{n} مادة مسجلة",
    "mat.btn_scan_qr": "مسح QR السريع",
    "mat.btn_new_item": "مادة جديدة",
    "mat.catalog_search": "البحث بالرمز أو اسم المادة…",
    "mat.col_code": "الرمز",
    "mat.col_name": "اسم المادة",
    "mat.col_cat": "الفئة",
    "mat.col_stock": "الكمية المتاحة",
    "mat.col_alert": "حد التنبيه",
    "mat.btn_use": "استخدام",
    "mat.no_articles": "لا توجد مواد مطابقة.",
    "mat.scanner_title": "مسح رمز QR للمادة",
    "mat.scanner_sim": "محاكي المسح السريع (قاعدة البيانات)",
    "mat.scanner_manual": "أو الإدخال يدويًا",
    "mat.use_title": "تسجيل حركة إخراج",
    "mat.use_stock_qty": "الكمية في المخزن: ",
    "mat.use_field_qty": "الكمية المراد سحبها",
    "mat.use_field_bpi": "PBO / BPI المخصص (اختياري)",
    "mat.use_field_note": "ملاحظة / سبب التخصيص",
    "mat.use_btn_submit": "إنشاء طلب السحب",
    "mat.add_title": "إضافة مادة جديدة للمخزن",
    "mat.add_field_code": "الرمز الفريد للمادة",
    "mat.add_field_name": "اسم المادة بالتفصيل",
    "mat.add_field_cat": "فئة المواد",
    "mat.add_field_unit": "وحدة القياس",
    "mat.add_field_stock": "المخزون الأولي",
    "mat.add_field_min": "الحد الأدنى للتنبيه",
    "mat.add_btn_submit": "إنشاء المادة في الكتالوج",

    // Users
    "users.title": "لوحة التحكم الإدارية",
    "users.subtitle": "إدارة مركزية SQLite، مزامنة Excel، سجلات التدقيق.",
    "users.loading": "جاري تحميل المستخدمين…",
    "users.badge": "مساحة مدير النظام",
    "users.tab_users": "إدارة المستخدمين",
    "users.tab_logs": "سجلات التدقيق",
    "users.tab_config": "إعداد النظام",
    "users.list_title": "المستخدمون المسجلون في قاعدة البيانات",
    "users.btn_create": "إنشاء حساب",
    "users.col_user": "المستخدم",
    "users.col_email": "البريد الإلكتروني",
    "users.col_role": "تعيين الدور",
    "users.col_status": "حالة الحساب",
    "users.col_actions": "الإجراءات",
    "users.status_active": "نشط",
    "users.status_suspended": "موقوف",
    "users.logs_title": "سجلات التدقيق ومراقبة النشاط",
    "users.log_action": "المستخدم {user} قام بإجراء.",
    "users.log_module": "الوحدة: {module}",
    "users.config_title": "الإعدادات العامة للإشراف",
    "users.config_detect": "الكشف التلقائي عن الأعطال",
    "users.config_detect_desc": "فحص شبكة GPON تلقائيًا كل 30 ثانية للكشف عن انقطاع الألياف.",
    "users.excel_sync": "مزامنة Excel ثنائية الاتجاه",
    "users.excel_sync_desc": "قارن الاختلافات الهيكلية بين ورقة Excel وقاعدة SQLite ftth.db، ثم ادمج التغييرات.",
    "users.excel_status": "جسر نشط",
    "users.excel_dropzone_title": "اسحب وأسقط ملف Excel الفني",
    "users.excel_dropzone_desc": "ملف Base de données (1).xlsx أو ملف هندسة الألياف (الأقصى 10 ميجا)",
    "users.excel_dropzone_btn": "تصفح الملفات",
    "users.excel_details_title": "الاختلافات المكتشفة (حل النزاعات)",
    "users.excel_details_count": "3 نزاعات",
    "users.excel_col_type": "النوع",
    "users.excel_col_element": "العنصر / الخاصية",
    "users.excel_col_sqlite": "القيمة الحالية (SQLite)",
    "users.excel_col_excel": "القيمة الجديدة (Excel)",
    "users.excel_btn_reset": "إعادة تعيين",
    "users.excel_progress_syncing": "جاري المزامنة...",
    "users.excel_success_title": "تمت مزامنة قاعدة بيانات SQLite بنجاح!",
    "users.excel_success_desc": "تم الانتهاء من دمج الملف. المشترك Block C30 وإحداثيات PBO BPI-A7 نشطة الآن.",
    "users.excel_btn_submit": "تطبيق الدمج وتحديث SQLite",
    "users.config_retention": "مدة الاحتفاظ بسجلات النظام",
    "users.config_retention_days": "{n} يوم",
    "users.modal_create_title": "إنشاء حساب جديد",
    "users.field_name": "الاسم الكامل",
    "users.field_email": "البريد الإلكتروني الفريد",
    "users.field_role": "الدور / الصلاحية",
    "users.field_password": "كلمة المرور",
    "users.btn_submit": "تسجيل المستخدم",

    // Map
    "map.title": "التصور الجغرافي للشبكة",
    "map.tab_zones": "المناطق",
    "map.tab_clusters": "العناقيد",
    "map.tab_cables": "الكابلات",
    "map.search_ph": "البحث عن موقع...",
    "map.layers_title": "طبقات الشبكة",
    "map.layer_style": "نمط الخريطة",
    "map.style_osm": "مخطط المدينة",
    "map.style_satellite": "عرض القمر الصناعي",
    "map.infra": "البنية التحتية",
    "map.layer_reliable": "المناطق الموثوقة",
    "map.layer_monitor": "المناطق تحت المراقبة...",
    "map.layer_lines": "الخطوط الضوئية",
    "map.layer_points": "نقاط الوصول",
    "map.layer_anomalies": "الشرائح المعطلة",
    "map.stats_title": "إحصائيات المنطقة المحددة",
    "map.stats_locations": "عدد المواقع:",
    "map.stats_faults": "الأعطال النشطة:",
    "map.stats_coverage": "التغطية:",
    "map.no_data": "لا توجد مواقع متوفرة.",

    // Roles
    "role.admin": "مدير النظام",
    "role.operator": "مشغل TT",
    "role.project_manager": "مدير المشروع",
    "role.technician": "تقني",

    // Common
    "common.na": "غير محدد",
    "common.search": "بحث…",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.close": "إغلاق",
    "common.confirm": "تأكيد",
    "common.loading": "جاري التحميل…",
    "common.empty": "لا توجد نتائج.",
    "common.lang_toggle": "FR",
  },
};

// ─── Provider ─────────────────────────────────────────────────────────────────
export function AppProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("ft_lang") as Lang) || "fr";
    }
    return "fr";
  });

  const [zone, setZoneState] = useState<Zone>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("ft_zone") as Zone) || "Toutes les zones";
    }
    return "Toutes les zones";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("ft_lang", l);
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = l;
  };

  const setZone = (z: Zone) => {
    setZoneState(z);
    localStorage.setItem("ft_zone", z);
  };

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string, vars?: Record<string, string | number>): string => {
    let str = translations[lang][key] || translations["fr"][key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, String(v));
      });
    }
    return str;
  };

  return (
    <AppContext.Provider value={{ lang, setLang, zone, setZone, t }}>
      {children}
    </AppContext.Provider>
  );
}

// ─── Hook ─────────────────────────────────────────────────────────────────────
export function useApp() {
  return useContext(AppContext);
}
